### ISSUE TITLE
Remove Tres preposition on components

### ISSUE THREAD

**Issue by Makio64** [Tresjs/tres#290]
### Description

Keep repeating Tres in front of the components reduce the readability and make it a bit "heavy" like the old times of THREE when we added THREE in front of all in the code.

### Suggested solution

change from
`TresMesh TresGeometry TresMeshBasicMaterial etc.. `

to
`Mesh Geometry MeshBasicMaterial`

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alvarosabu** [comment]
There is a reason for that. If you add a `<PerspectiveCamera />` to the template your IDE will auto-import the class `PerspectiveCamera` from three causing an error because is not a valid vue component for the custom renderer. Name collision is important to avoid so this is often used in UI libs for example: Vuetify `<v-btn>` or `IonButton` on Ionic

It also helps differentiate which components belong inside of the canvas renderer and which ones on Vue. 

We could adopt an alias in the future to use `mesh` and `perspectiveCamera` with the first letter in lowercase as R3F does as optional, but implementing this at this point will be a huge breaking change.

**Comment by Makio64** [comment]
@alvarosabu I think with auto-import plug-in in vite it'll fix the problem as the import from component would not be requires and it ll avoid conflict. 

Also Troisjs didn't seems to have this problem

**Comment by alvarosabu** [comment]
TroisJS is a manual wrapper, they implemented all the components in the repo itself.

TresJS works with a custom renderer API, that's why you don't see any actual component apart of the TresCanvas in the core. 

The custom render check if the component has the Tres prefix to convert it to a ThreeJS instances.

Both projects are fundamentally different.
