### ISSUE TITLE
onBeforeCompile prop of material doesn't work

### ISSUE THREAD

**Issue by enpitsuLin** [Tresjs/tres#360]
### Describe the bug

For class  [`Material`](https://threejs.org/docs/index.html#api/en/materials/Material)  we have [onBeforeCompile ](https://threejs.org/docs/index.html#api/en/materials/Material.onBeforeCompile)method, R3f provide onBeforeCompile prop to use that ([example](https://codesandbox.io/s/r3f-basic-demo-forked-ftwcm)), and I think Tresjs should have something like this.

I tried to use `@beforeCompile` will warn 
![image](https://github.com/Tresjs/tres/assets/29378026/e9e6de6d-8e35-4a95-8b66-6fb4b9fba3fd)

and `onBeforeCompile` both don't work, I guess this might be a bug or this is a feature doesn't implement yet?

I provide a reproduction with a Codesandbox copy from [the official playground](https://github.com/Tresjs/playground/tree/main/components/content/basic-shaders), just run and see no stdout which should have

### Reproduction

https://codesandbox.io/p/sandbox/hopeful-goodall-y86d74?file=%2Fsrc%2FApp.vue%3A44%2C9

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Try `<Material on-before-compile="[...args]" />`

**Comment by enpitsuLin** [comment]
@alvarosabu  onBeforeCompile is a function that was not iterable

I assign it to the property manually then it works. 

```ts
watchPostEffect(() => {
  if (materialRef.value) materialRef.value.onBeforeCompile = onBeforeCompile;
});
```

**Comment by alvarosabu** [comment]
@Tinoooo would make sense that we map `on` events to native vue events?

**Comment by Tinoooo** [comment]
> @Tinoooo would make sense that we map `on` events to native vue events?

@alvarosabu Yes, I think this could be a handy feature ☺️

**Comment by ThimoDEV** [comment]
@Tinoooo , @alvarosabu  Where would I have to start searching to map those events. Is that a responsibility of the custom renderer?

**Comment by andretchen0** [comment]
Just chiming in. 

Ran into this as well, but in my case with `onBeforeRender`. I think it'd be handy to be able to set the callback via props.

**Comment by andretchen0** [comment]
@ThimoDEV

> Where would I have to start searching to map those events. 

I'd start with `patchProp` in `src/core/nodeOps.ts`.

**Comment by andretchen0** [comment]
I started looking into this.

With a scene like ...

```
<Object3D :on-before-render="console.log">
  ...
</Object3D>
```

... and stepping through `src/core/nodeOps.ts`,  [you end up at this line](https://github.com/Tresjs/tres/blob/1650b345eceecfb9a20d873a01481eddd0c63cba/src/core/nodeOps.ts#L237).

Here it is in the debugger, with some watch expressions on the right showing the pertinent values:

<img width="1134" alt="Screenshot 2024-04-08 at 01 16 56" src="https://github.com/Tresjs/tres/assets/20469369/d1ddc5ee-9997-4fd6-8999-064aab04ded8">

It's *calling* ...

```ts
node[finalKey](value)    // i.e., object3d['onBeforeRender'](console.log)
```

... but what's desired here (at least in this issue, if not generally) is *setting* ...

```ts
node[finalKey] = value   // i.e., object3d['onBeforeRender'] = console.log
```

## Context

Looking through the git history, that chunk of code has been calling rather than setting ever since it was added to the codebase. Here are the relevant commits:

* https://github.com/Tresjs/tres/commit/fa072cddc0fca4c1862a49fa2877d3ef5c96dbd2
* https://github.com/Tresjs/tres/commit/c07d963bd50910f9df519db05ed7f1a496ff03cc

## Question

* @alvarosabu , do you happen to remember what the use case is for calling here, rather than setting?
* If there's a use case for calling, can we carve that out with a conditional?

**Comment by andretchen0** [comment]
## Context

I came across at least one common use case for calling here. 

Something like `<PerspectiveCamera :look-at="[1, 2, 3]" />`. Under the hood, that needs to call `lookAt()`. 

Notably, this doesn't appear to work in R3F/Drei. In R3F, you have to get a reference to the camera and call `lookAt()`. That's *probably* a more coherent approach, since [templates are supposed to be declarative](https://vuejs.org/guide/essentials/template-syntax.html). 

But since we're already *calling* we should probably continue to call, at least where it's obvious that setting isn't desired.

## Fix?

To accommodate setting functions, in `src/core/nodeOps.ts`, we could do something like changing this:

```ts
      if (isFunction(target)) {
        // don't call pointer event callback functions
        if (!supportedPointerEvents.includes(prop)) {
          if (Array.isArray(value)) { node[finalKey](...value) }
          else { node[finalKey](value) }
        }
        return
      }
```

... to ...

```ts
      if (isFunction(target)) {
        // don't call pointer event callback functions
        if (!supportedPointerEvents.includes(prop)) {
          if (isFunction(value)) {
              // NOTE: Both target and value are functions. Set target to value.
              node[finalKey] = value
          }
          else if (Array.isArray(value)) { node[finalKey](...value) }
          else { node[finalKey](value) }
        }
        return
      }
```

## Breaking

That *will* break code like:

```vue
<Object3D :traverse="myTraverseCallback" />
```

But to me anyway, this clearly not declarative and doesn't belong in a template.

However, if we wanted to, we could work around it for this case and the other `on...` callbacks by being more specific with the predicate:

```ts
          if (isFunction(value) && finalKey.startsWith('on')) {
              node[finalKey] = value
          }
```

That keeps almost all of the current functionality in place, but it seems overly specific, making it hard to intuit without digging into the source.

----

## Feedback?

Any thoughts here?

**Comment by enpitsuLin** [comment]
So it's some thing like that we are calling `lootAt()` by props rather method on instance, is there other case like that?

> we could work around it for this case and the other `on...` callbacks by being more specific with the predicate:

I think it's best solution. 

In my opinion, almost use case about `on...` property in Object3D should be used to be assigned, not to calling them, it was a callback runs inner that can be override by user

**Comment by andretchen0** [comment]
> So it's some thing like that we are calling lootAt() and traverse() by props rather method on instance, is there other case like that?

I haven't found others exactly like that in `Mesh`. But similar to that is:

```
<TresMesh :position="[1, 2, 3]" />
```

In order to pretend that's declarative, we have to *call* rather than *set* behind the scenes. Something like:

```
mesh.position.set(... [1, 2, 3])
```

and not 

```
mesh.position = [1, 2, 3]
```

**Comment by andretchen0** [comment]
> I think it's best solution.

I'll submit a PR.

**Comment by enpitsuLin** [comment]
seem done, it's closed
