### ISSUE TITLE
Memory leak caused by non disposed scene, when using routes

### ISSUE THREAD

**Issue by fakedob** [Tresjs/tres#449]
### Describe the bug

In our project, we use a bit big bigger models and we test our app on mobile browsers. While observing the memory, it became clear that unmounting the TresCanvas, does not properly dispose the scene and some (maybe all) internal objects. So navigating in and out a few times on iOS device, cause the page to crash and reload, because it runs out of memory.

<img width="1728" alt="Screenshot 2023-11-19 at 20 15 16" src="https://github.com/Tresjs/tres/assets/8687970/af02ab7d-7e0f-4c9a-bc87-5b4fd49c9c21">

Unfortunately, my understanding of three.js is not much, but I had similar issues in the past and it was related to the way the scene and objects, that were added to the scene, being not properly disposed. Its possible that some references to some internal TresJS objects are also the cause of the issue. I just dont know.

Its also possible that I am missing something in the way I use the framework (which will be the best for me), so hopefully someone can give me a hand with this.

Thank you!

### Reproduction

https://stackblitz.com/edit/tresjs-basic-tmk778

### Steps to reproduce

To reproduce, open the reproduction link in a Chromium browser and use the `Memory` tab in the dev tools. 
At the top of the web page, you will find a basic navigation, that routes into two separate pages, where "The Experience" loads the TresCanvas and "Home" is used to unmount the other one.

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Thanks for raising this @fakedob I will take a look to it 🙏🏻

**Comment by alvarosabu** [comment]
@fakedob can you confirm for me this is only happening with 3D models? If you use geometries with textures you get the same result? Just to narrow down I'm doing some tests currently

**Comment by alvarosabu** [comment]
Hey @fakedob I just tried the solution they provided but I am having trouble measuring the before and after, looking at the total allocated size remains similar but then looking for specific classes inside they are removed when dispose of.

How do you check if the geometries, materials, and textures have been properly disposed of and free out of memory?

**Comment by alvarosabu** [comment]
Hi @yyx990803 thanks for offering your help. Just added you here for proper context 

When using `v-if` on a component belonging to the Tres custom renderer, the `remove` method of the `nodeOps.ts` is called and the properties like geometry and material are disposed from GPU and removed from memory (CPU) https://github.com/Tresjs/tres/blob/bugfix/449-memory-management/src/core/nodeOps.ts#L184-L195

https://github.com/Tresjs/tres/assets/4699008/02a7834d-77c8-4756-9878-b63debfbe16f

When navigating to a new route, `remove` method is not called (I guess that's expected) but the `onUnmounted` method of the `<TresCanvas />` (the component responsible for rendering the tres custom renderer) is being called, however, for some reason by manual disposing of the scene (similar to what happens inside the `remove` method) doesn't seem to free the references of the properties on the memory. 


https://github.com/Tresjs/tres/assets/4699008/94e902e1-a9ba-4516-8fdb-1b81b4676858

My rough guess is that they continue being referenced on the custom renderer and that's why the garbage collector cannot free them but I'm not sure of this. No idea how to "dispose" the custom render.

Here is a reproduction link https://stackblitz.com/edit/tresjs-basic-ejbcex?file=package.json,src%2Fmain.ts,src%2Fpages%2Findex.vue,src%2Fpages%2Fempty.vue,src%2Fstyle.css

To debug maybe is gonna be easier to clone https://github.com/Tresjs/tres/tree/bugfix/449-memory-management and run the playground `npm run dev` and go to `/perf/` route. 

Thanks again 🙏🏻

**Comment by alvarosabu** [comment]
Hey @fakedob so we still investigating, we did some improvements but the issue of memory allocation not being released on route change is still there and it doesn't seem trivial. I will get back to you as soon we have news. Sorry

**Comment by Sea-DH1** [comment]
> Hey @fakedob so we still investigating, we did some improvements but the issue of memory allocation not being released on route change is still there and it doesn't seem trivial. I will get back to you as soon we have news. Sorry

I think this method can be used to create a calling method inside the primitive and call it directly when the scene is destroyed.
https://threejs.org/manual/#en/cleanup

**Comment by fakedob** [comment]
Thank you so much for your help guys, I will try this method and hope it will do the trick. Temporarily, as a workaround, I am loading a separate page into an iframe and control it via post messages. It is very limiting approach, but at least it doesnt crash the web app on mobile.

I will let you know how does it behave when calling the cleanup method asap.

**Comment by fakedob** [comment]
No, unfortunately, I didn't find an easy way around. The way I approached this problem finally, was to load the thres renderer into an iframe, which basically runs another window process, thus, when navigating away, the browser takes care of its memory. I know it looks a bit dirty, but it works. Just to give you another hint, I made a 2 way communication between the main and the child process to pass data of what needs to be loaded etc and control it as I would do with APIs. I hope this information help you, good luck.

**Comment by JLK-666** [comment]
@alvarosabu  Hello, I also encountered this problem. Is it solved now

**Comment by alvarosabu** [comment]
> @alvarosabu Hello, I also encountered this problem. Is it solved now

Is it a question?

**Comment by JLK-666** [comment]
> > @alvarosabu Hello, I also encountered this problem. Is it solved now
> 
> Is it a question?
yes，I used your new dispose() function but it didn't solve the problem

**Comment by JLK-666** [comment]
> > @alvarosabu Hello, I also encountered this problem. Is it solved now
> 
> Is it a question?
@alvarosabu 
 yes，I used your new dispose() function but it didn't solve the problem
