### ISSUE TITLE
Pointer EventManager state

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#515]
### Description

As a developer using TresJS, I would like to have an Event Management solution with the following features:

- Support for:
  - onClick
  - onContextMenu (rightClick)
  - onDoubleClick
  - onWheel
  - onPointerDown
  - onPointerUp
  - onPointerLeave
  - onPointerMove
  - onPointerCancel
  - onLostPointerCapture
- Event prioritization 
- primitive pointer events
- Event bubbling and propagation #501 #426 

# Propagation through intersected objects

Raycasting-Based Interaction: Tres should use Three.js's raycasting to determine which objects are interacted with. A ray is cast from the camera through the mouse position into the 3D space, and intersections with objects are calculated.

Simulated Bubbling: When an event occurs, Tres might propagate it through objects based on their spatial arrangement (like from child to parent), but this is based on the raycast hits and not a strict parent-child hierarchy as in the DOM.

Meaning that stop propagation is based on occlusion

![event propagation](https://github.com/Tresjs/tres/assets/4699008/352598c2-7c51-4910-866d-6abb994e1e74)

If the object is a Group or a model consistent with several meshes, the same concept applies, the closest mesh to the camera stops the propagation

![group and model propagation events](https://github.com/Tresjs/tres/assets/4699008/54d767f5-d237-4a99-b25a-53c93487c075)

### Suggested solution

# Current solution uses:

- `useRaycaster` https://github.com/Tresjs/tres/blob/main/src/composables/useRaycaster/index.ts
- `usePointerEventHandler` https://github.com/Tresjs/tres/tree/main/src/composables/usePointerEventHandler

Register of events is being done here 
https://github.com/Tresjs/tres/blob/main/src/composables/usePointerEventHandler/index.ts#L57-L62

```ts
const registerObject = (object: Object3D & EventProps) => {
  const { onClick, onPointerMove, onPointerEnter, onPointerLeave } = object

  if (onClick) objectsWithEventListeners.click.set(object, onClick)
  if (onPointerMove) objectsWithEventListeners.pointerMove.set(object, onPointerMove)
  if (onPointerEnter) objectsWithEventListeners.pointerEnter.set(object, onPointerEnter)
  if (onPointerLeave) objectsWithEventListeners.pointerLeave.set(object, onPointerLeave)
}

  // to make the registerObject available in the custom renderer (nodeOps), it is attached to the scene
  scene.userData.tres__registerAtPointerEventHandler = registerObject
  scene.userData.tres__deregisterAtPointerEventHandler = deregisterObject

  scene.userData.tres__registerBlockingObjectAtPointerEventHandler = registerBlockingObject
  scene.userData.tres__deregisterBlockingObjectAtPointerEventHandler = deregisterBlockingObject
```

These are then used on the renderer by saving them on the `userData` of the scene object

```ts
insert(child, parent) {
  if (parent && parent.isScene) scene = parent as unknown as TresScene

  const parentObject = parent || scene

  if (child?.isObject3D) {
    if (
      child && supportedPointerEvents.some(eventName => child[eventName])
    ) {
      if (!scene?.userData.tres__registerAtPointerEventHandler)
        throw 'could not find tres__registerAtPointerEventHandler on scene\'s userData'

      scene?.userData.tres__registerAtPointerEventHandler?.(child as Object3D)
    }
  }
```

https://github.com/Tresjs/tres/blob/main/src/core/nodeOps.ts#L102

# Desired solution

A state/store to manage the events

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
Imagine each mesh below is visible on screen and not occluded by any other meshes.

```vue
<TresCanvas :on-click="() => console.log('Scene')">
  <TresGroup :on-click="() => console.log('Group')">
    <Sphere :on-click="() => console.log('Sphere')">
        <Torus :on-click="() => console.log('Torus')" />
        <TorusRing />
    </Sphere>
    <Box />
  </TresGroup>
</TresCanvas>
```

What should be in the console when ...

* Torus is clicked?
* TorusRing is clicked?
* Sphere is clicked?
* Box is clicked?
* the background is clicked?

**Comment by alvarosabu** [comment]
Hi @andretchen0 regarding your example

- TresCanvas is not meant to have a click event
- Sphere, Torus, and TorusRing are meant to be meshs and siblings ? You can pass geometries and materials to a mesh, but not children to a sphere right? 

In the case that you have a group and the children are not occluding, (example you click on the sphere inside of the group) then it will trigger the console for Sphere and then the on for Group

![Screenshot 2024-01-24 at 11 06 09](https://github.com/Tresjs/tres/assets/4699008/f2561d22-6f75-4507-96d2-578bff034006)

In r3f (we don't have stopPropagation yet) If you do `<Sphere @click="(e) => e.stopPorpagation()">` then only the Sphere should prompt, group will remain silent.

**Comment by andretchen0** [comment]
Hey @alvarosabu ,

> * You can pass geometries and materials to a mesh, but not children to a sphere right?

Maybe we're talking about different things. I should have included working code. Here's a [StackBlitz](https://stackblitz.com/edit/tresjs-text3d-cientos-bf6huz?file=src%2Fcomponents%2FTheExperience.vue) with the kind of nesting I'm talking about.

<img width="374" alt="299314050-53c975a7-b18e-4145-ab2c-79cb80923e32" src="https://github.com/Tresjs/tres/assets/20469369/52f20ab9-0140-4a74-975e-7766344fc801">

So, with that kind of setup, where the `Object3D`s are nested, what happens here if Box2 is clicked? (Box2 doesn't have an event handler, but its parent does.)

```vue
<Box> <!-- Box0 -->
    <Box :on-click="() => alert('Box1')"> <!-- Box1 -->
        <Box /> <!-- Box2 -->
    </Box>
</Box>
```

Will Box1's `:on-click` be triggered?

For a more concrete scenario, imagine an on-screen bicycle made of different, nested `Object3D`s. The on-screen bicycle should be clickable. Would the following code make the whole bicycle clickable? I.e., would clicking any one of `<Bicycle />`, `<Wheel />`, `<Pedals />`, `<Handlebars />`, `<Bell />` call `() => alert("Bicycle")`?

```vue
<Bicycle :on-click="() => alert('Bicycle')">
    <Wheel />
    <Pedals />
    <Handlebars>
        <Bell />
        <Wheel />
    </Handlebars />
</Bicycle>
```

This is what's familiar to me, since it's the way the DOM works. 

If we don't go that route, the alternative for making the whole bicycle clickable is as follows, but it's not as familiar to me, and probably not as user-friendly.

```vue
<Bicycle :on-click="() => alert('Bicycle')">
    <Wheel :on-click="() => alert('Bicycle')" />
    <Wheel :on-click="() => alert('Bicycle')" />
    <Pedals :on-click="() => alert('Bicycle')" />
    <Handlebars :on-click="() => alert('Bicycle')">
        <Bell :on-click="() => alert('Bicycle')" />
    </Handlebars>
</Bicycle>
```

**Comment by garrlker** [comment]
> ```
> <TresCanvas :on-click="() => console.log('Scene')">
>   <TresGroup :on-click="() => console.log('Group')">
>     <Sphere :on-click="() => console.log('Sphere')">
>         <Torus :on-click="() => console.log('Torus')" />
>         <TorusRing />
>     </Sphere>
>     <Box />
>   </TresGroup>
> </TresCanvas>
> ```


> What should be in the console when ...
*Note if we completely follow convention, then we would also log `Scene` in these examples

> Torus is clicked?
```sh
Torus
Sphere
Group
```

> TorusRing is clicked?
```sh
Sphere
Group
```

> Sphere is clicked?
```sh
Sphere
Group
```

> Box is clicked?

```sh
Group
```

> the background is clicked?
```sh
```

> 
> ```
> <Box> 
>     <Box :on-click="() => alert('Box1')"> 
>         <Box /> 
>     </Box>
> </Box>
> ```
> 
> Is Box2 clickable? If so and it's clicked, will Box1's `:on-click` be triggered?
> 
> Assuming we're doing events like the DOM does, it seems to me that the answer to both is "yes". I just want to make sure my understanding is correct.

Yes if you click Box2, Box1 would receive the event. 

To add on to this, if you lined up the view so that Box2 was occluding Box1/Box0 then clicked on Box2(with no stopProgation), Box1's event handler would get called *twice*
* Once because Box2's event would bubble up to Box1 since it is Box2's parent
* Secondly, because once Box2's `onClick` event finishes propagating up the scene the next object hit by the ray will also have an onClick event fired

**Comment by andretchen0** [comment]
@garrlker Thanks for the answers and clarifications. That's making sense now.

About bubbling events to `Scene`, I think it's really handy. One (useful to me) pattern for DOM events is to attach a handful of listeners to the document body and to handle events bubbled up from children there. In our case, that could be handled with a `TresGroup` wrapping all other objects, but I guess I don't currently see a reason why we wouldn't also bubble all the way to `Scene`. (That doesn't mean there isn't a good reason not to do that though!)

Maybe relevant: [R3F has an event called `onPointerMissed` that fires when no mesh is hit by a click/touch.](https://docs.pmnd.rs/react-three-fiber/api/events)

----

Fwiw, I haven't looked at the R3F source, but at least in this [R3F StackBlitz](https://stackblitz.com/edit/vitejs-vite-ggmpvs?file=src%2FApp.tsx,src%2FApp.css,src%2Fcomponents%2FPlane.tsx) `onPointerEnter` and `onPointerLeave` don't fire unless the pointer is moved.

**Comment by garrlker** [comment]
> @garrlker Thanks for the answers and clarifications. That's making sense now.
> 

Anytime! 

> 
> About bubbling events to `Scene`, I think it's really handy. One (useful to me) pattern for DOM events is to attach a handful of listeners to the document body and to handle events bubbled up from children there. In our case, that could be handled with a `TresGroup` wrapping all other objects, but I guess I don't currently see a reason why we wouldn't also bubble all the way to `Scene`. (That doesn't mean there isn't a good reason not to do that though!)

I also think it could be handy, thought I'm not quite sure how I'd use it yet. I think it's better we include it than not 

> 
> Maybe relevant: [R3F has an event called `onPointerMissed` that fires when no mesh is hit by a click/touch.](https://docs.pmnd.rs/react-three-fiber/api/events)
> 

Good catch! We definitely want to include that event 


> I haven't looked at the R3F source, but at least in this [R3F StackBlitz](https://stackblitz.com/edit/vitejs-vite-ggmpvs?file=src%2FApp.tsx,src%2FApp.css,src%2Fcomponents%2FPlane.tsx) `onPointerEnter` and `onPointerLeave` don't fire unless the pointer is moved.

Those events don't fire unless the pointer is moved, _by default_

You can force the ray cast to fire with the mouse's last know coordinates in a useFrame callback, and if a moving object moves into those coordinates those events will be triggered

**Comment by andretchen0** [comment]
> Those events don't fire unless the pointer is moved, _by default_

Gotcha! Thanks!

**Comment by andretchen0** [comment]
Here's a StackBlitz showing a current problem with events that we will hopefully resolve with this issue:

https://stackblitz.com/edit/tresjs-basic-d6y7tr?file=src%2FApp.vue

There are two boxes in the `Scene`. 

* The red box is wrapped in a `TresGroup`. The `TresGroup` has an `@click` attribute. The red box does not have its own `@click` attribute.
* The green box is not wrapped in a `TresGroup`. The green box has its own `@click` attribute.

## Expected behavior

Both boxes should be clickable. Clicking the red box should call the `@click` on the parent `TresGroup`. 

## Actual behavior

* The green box's `@click` is called when it is clicked.
* The red box's `@click` is not called when it is clicked.

## Vue equivalent

Here's [an equivalent Vue-only playground](https://play.vuejs.org/#eNp9UsFuwjAM/ZUoF0BC7YEbKmhjQtN22Ca2Yy6Qel0gTaLEYZUQ/z43BVZpU2/2e895z1ZO/N657BiBz3kRpFcOWQCMbilMkXcAldQg1E5vEahjrCjVkd1JreRhIfgYJmyxZNKaYDVk2lbjkYeS7WwzmjKYCJ6GaGwXEa25dIxtSLSyzYXMe2yRk0NXdeiwW+UBzF+/xwRfHHrvF3lvGz7lGOi1T1Vl+2ANXeLU6gWXtnZKg391qMhN8DlLTMtttbbfzwlDH2F6xeUXyMM/+D40LSb4m4cA/giC3zjc+gqwo9fvL9BQfSNrW0ZN6gFyA3SJ2GbsZKtoSord06W0T7WzHpWpPsK6QTDhulQbtFWek15w+g4PA6v/xp1lszQnzJmffwDTHrz0). Both 'boxes' are clickable. The `@click` prop falls through properly.


### Reference

[Vue docs on fallthrough attributes](https://vuejs.org/guide/components/attrs.html#v-on-listener-inheritance)

### Meta


Should this be opened as a separate issue and referenced here?

**Comment by Tinoooo** [comment]
@andretchen0 What you are describing is what was discussed in #426 . I agree with you. The fix should be provided in the scope of this issue.

**Comment by andretchen0** [comment]
Related: #527

**Comment by garrlker** [comment]
It's still WIP, but I've pushed up my changes so that you all can start reviewing the code and test out the changes

There is a playground example wired up at `/raycaster/propogation`. Wire up as many pointer events as you can and have fun :)

So far I've implemented
### Events
* onClick :white_check_mark:
* onContextMenu :white_check_mark:
* onPointerDown :white_check_mark:
* onPointerUp :white_check_mark:
* onPointerLeave/onPointerOut :white_check_mark:
* onPointerEnter/onPointerOver :white_check_mark:
* onDoubleClick :white_check_mark:
* onWheel :white_check_mark:
* onPointerCancel ❌
* onLostPointerCapture ❌
* onPointerMissed ❌

### Features
Primitives are supported (and possibly anything else in the scene judging by #527 ) :white_check_mark:
* Event Prioritization ❌
* TresCanvas Events :white_check_mark:
* Forced Raycasts ❔- might work, I've written the `forceUpdate` function, but still figuring out how to expose it to a component for testing

### Event Propogation
  * Raycast :white_check_mark:
  * Scene Hierarchy :white_check_mark:

Event HMR is broken right now so that needs to be fixed before merge as well

Besides that, I wasn't able to create this in a store-ish approach. I unhooked the current system so I could work on it free from bias but the `useEventStore` ended up being a similar approach to the current `usePointerEventHandler`

@alvarosabu / @Tinoooo  I may need a bit of guidance on how you two were wanting the use of said store to look like to try and work this event system into what ya'll were expecting.

### Changes

1. Now we call intersectObjects() over the whole scene. We needed to support any object whether or not it had an event listener and that was the easiest way to do it. This is why Primitives/Sprites/etc are now supported. I've got some ideas for how to make this more performant that involve being extra smart in the renderer and nodeOps, but those are outside of the scope of this PR for now

2. `useEventStore` completely sidesteps the nodeOps Object3d insert/remove operations by only executing when eventHooks fire in `useRaycaster`

3. This supports the `.stop` event modifier for blocking events, **and** this supports multiple event listeners on a single object3D
