### ISSUE TITLE
Unable to use custom provide inject

### ISSUE THREAD

**Issue by Sea-DH1** [Tresjs/tres#537]
### Describe the bug

Custom injection cannot be used in components
After checking the source code, it seems that except for the TresCanvas component, other components cannot be seen in devTools, so there is no concept of sub-components.
Need to extend the context with a custom injection?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-8p7urb?file=src%2Fcomponents%2FCustomizeContext.vue

### System Info

```shell
system:
    OS: windows
    CPU: (8) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.2GHz
    Memory: 0 Bytes / 0 Bytes
  Binaries:
    Node: 18.18.0
    Yarn: 1.22.19
    npm: 9.4.2
    pnpm: 8.14.0
  npmPackages:
    @tresjs/cientos: 3.7.0 => 3.7.0 
    @tresjs/core: 3.7.0 => 3.7.0 
    vite: ^5.0.12 => 5.0.12
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi, @Sea-DH1 this is a design limitation, the `CustomizeContext.vue` component belongs to the Vue renderer while everything inside of TresCanvas is another renderer (the custom renderer for threejs), they have different contexts.

That is also the reason you can't see the components inside the `TresCanvas`, because VueDevtools component tab is not meant to work with custom renderer objects.

To be able to inspect your components, a custom tab for vue devtools has been available since 3.7.0:

https://github.com/Tresjs/tres/assets/4699008/bc203106-fe67-41e8-a8b6-dd7df2edd6f2

**Comment by Sea-DH1** [comment]
But in the CustomizeContext.vue component, the custom provide cannot be obtained

**Comment by alvarosabu** [comment]
@Sea-DH1 as of now you can't share context between the Vue renderer and the Tres renderer. You can use a normal state for it.

**Comment by Sea-DH1** [comment]
@alvarosabu 
If the component level is deep, it is not very convenient to use the status
