### ISSUE TITLE
intersect only objects with events registered

### ISSUE THREAD

**Issue by kanocence** [Tresjs/tres#736]
### Description

I created a mesh using `Three.js` and added it to the scene with `context.scene.add()`. How can I add a click event to it? 
Initially, I could directly write `mesh.onClick = clickMesh`, but the [#714](https://github.com/Tresjs/tres/pull/714) submission restricted this behavior.

### Suggested solution

Maybe you could extend the `context.scene`.

### Additional context

@tresjs/core@4.0.2

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JakobHock** [comment]
Event's can be added via the template like shown in the [docs](https://docs.tresjs.org/api/events).

I'm not quite sure what issue you are experiencing. Can you provide a reproduction?

**Comment by alvarosabu** [comment]
Hi @kanocence the way to add event handlers is through the template by passing the event handlers like you would do in vue. We don't provide an interface to add event handlers programmatically to objects because is not the normal flow of a TresJS app.

You could add your object to the scene graph by using `primitives` and add the event handler there https://docs.tresjs.org/advanced/primitive
